-- 샘플 데이터: 개발/테스트용 (비밀번호: password). CommandLineRunner가 비밀번호 동기화.
INSERT INTO users (student_id, username, password, nickname, total_assets, investment_amount, profit_loss, profit_loss_rate) VALUES
('25000002', '25000002', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Test User', 10000000, 10000000, 0, 0);

-- 종목 검색(API)용 stock_master 시드. 비어 있으면 검색 결과 없음. 전체 목록은 importer 프로필 1회 실행으로 적재.
-- H2: MERGE로 재기동 시에도 중복 오류 없음.
MERGE INTO stock_master (code, std_code, name_kr, market, updated_at) KEY(code) VALUES
('005930', NULL, '삼성전자', 'KOSPI', CURRENT_TIMESTAMP),
('000660', NULL, 'SK하이닉스', 'KOSPI', CURRENT_TIMESTAMP),
('035420', NULL, 'NAVER', 'KOSPI', CURRENT_TIMESTAMP),
('051910', NULL, 'LG화학', 'KOSPI', CURRENT_TIMESTAMP),
('006400', NULL, '삼성SDI', 'KOSPI', CURRENT_TIMESTAMP),
('035720', NULL, '카카오', 'KOSPI', CURRENT_TIMESTAMP),
('068270', NULL, '셀트리온', 'KOSPI', CURRENT_TIMESTAMP),
('207940', NULL, '삼성바이오로직스', 'KOSPI', CURRENT_TIMESTAMP),
('005380', NULL, '현대차', 'KOSPI', CURRENT_TIMESTAMP),
('000270', NULL, '기아', 'KOSPI', CURRENT_TIMESTAMP),
('105560', NULL, 'KB금융', 'KOSPI', CURRENT_TIMESTAMP),
('055550', NULL, '신한지주', 'KOSPI', CURRENT_TIMESTAMP),
('032830', NULL, '삼성생명', 'KOSPI', CURRENT_TIMESTAMP),
('003550', NULL, 'LG', 'KOSPI', CURRENT_TIMESTAMP),
('012330', NULL, '현대모비스', 'KOSPI', CURRENT_TIMESTAMP),
('066570', NULL, 'LG전자', 'KOSPI', CURRENT_TIMESTAMP),
('000810', NULL, '삼성화재', 'KOSPI', CURRENT_TIMESTAMP),
('009150', NULL, '삼성전기', 'KOSPI', CURRENT_TIMESTAMP),
('247540', NULL, '에코플라스틱', 'KOSDAQ', CURRENT_TIMESTAMP),
('086520', NULL, '에코프로비엠', 'KOSDAQ', CURRENT_TIMESTAMP);

-- 나만의 ETF 통합 자산 검색/검증용 마스터.
-- 미국 전체 종목은 운영 데이터 적재로 확장한다. 아래 값은 기본 개발/테스트 시드다.
MERGE INTO asset_master (asset_id, asset_type, name, symbol, market, currency, active, backtest_enabled, price_source_status, last_price_verified_at, last_price_error, created_at, updated_at) KEY(asset_id) VALUES
('US_AAPL', 'STOCK', 'Apple Inc.', 'AAPL', 'NASDAQ', 'USD', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_MSFT', 'STOCK', 'Microsoft Corp.', 'MSFT', 'NASDAQ', 'USD', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_NVDA', 'STOCK', 'NVIDIA Corp.', 'NVDA', 'NASDAQ', 'USD', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_TSLA', 'STOCK', 'Tesla Inc.', 'TSLA', 'NASDAQ', 'USD', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_AMZN', 'STOCK', 'Amazon.com Inc.', 'AMZN', 'NASDAQ', 'USD', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_GOOGL', 'STOCK', 'Alphabet Inc.', 'GOOGL', 'NASDAQ', 'USD', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_META', 'STOCK', 'Meta Platforms Inc.', 'META', 'NASDAQ', 'USD', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_AVGO', 'STOCK', 'Broadcom Inc.', 'AVGO', 'NASDAQ', 'USD', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_AMD', 'STOCK', 'Advanced Micro Devices Inc.', 'AMD', 'NASDAQ', 'USD', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_JPM', 'STOCK', 'JPMorgan Chase & Co.', 'JPM', 'NYSE', 'USD', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_KO', 'STOCK', 'Coca-Cola Co.', 'KO', 'NYSE', 'USD', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_005930', 'STOCK', '삼성전자', '005930', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_000660', 'STOCK', 'SK하이닉스', '000660', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_035420', 'STOCK', 'NAVER', '035420', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_051910', 'STOCK', 'LG화학', '051910', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_006400', 'STOCK', '삼성SDI', '006400', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_035720', 'STOCK', '카카오', '035720', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_068270', 'STOCK', '셀트리온', '068270', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_207940', 'STOCK', '삼성바이오로직스', '207940', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_005380', 'STOCK', '현대차', '005380', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_000270', 'STOCK', '기아', '000270', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_105560', 'STOCK', 'KB금융', '105560', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_055550', 'STOCK', '신한지주', '055550', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_032830', 'STOCK', '삼성생명', '032830', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_003550', 'STOCK', 'LG', '003550', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_012330', 'STOCK', '현대모비스', '012330', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_066570', 'STOCK', 'LG전자', '066570', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_000810', 'STOCK', '삼성화재', '000810', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_009150', 'STOCK', '삼성전기', '009150', 'KOSPI', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_247540', 'STOCK', '에코플라스틱', '247540', 'KOSDAQ', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('KRX_086520', 'STOCK', '에코프로비엠', '086520', 'KOSDAQ', 'KRW', TRUE, TRUE, 'VERIFIED', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('BOND_KR_GOV_3Y', 'BOND', '국고채 3년', 'BOND_KR_GOV_3Y', 'BOND', 'KRW', TRUE, TRUE, 'PROXY', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('BOND_KR_GOV_10Y', 'BOND', '국고채 10년', 'BOND_KR_GOV_10Y', 'BOND', 'KRW', TRUE, TRUE, 'PROXY', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('BOND_US_TREASURY_10Y', 'BOND', '미국 국채 10년', 'BOND_US_TREASURY_10Y', 'BOND', 'USD', TRUE, TRUE, 'PROXY', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('BOND_US_TREASURY_20Y', 'BOND', '미국 국채 20년', 'BOND_US_TREASURY_20Y', 'BOND', 'USD', TRUE, TRUE, 'PROXY', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CASH_KRW', 'CASH', '원화 현금', 'KRW', 'CASH', 'KRW', TRUE, TRUE, 'PROXY', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CASH_USD', 'CASH', '달러 현금', 'USD', 'CASH', 'USD', TRUE, TRUE, 'PROXY', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 자산 alias 검색용 시드. Nasdaq 원본에는 한글명이 없으므로 대표 종목/자산의 한글 검색어를 별도로 관리한다.
MERGE INTO asset_alias (asset_id, alias, locale, source, active, created_at, updated_at) KEY(asset_id, alias) VALUES
('US_AAPL', '애플', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_AAPL', '아이폰', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_MSFT', '마이크로소프트', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_MSFT', '윈도우', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_NVDA', '엔비디아', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_NVDA', '그래픽카드', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_TSLA', '테슬라', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_TSLA', '전기차', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_AMZN', '아마존', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_AMZN', 'AWS', 'en-US', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_GOOGL', '구글', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_GOOGL', '알파벳', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_META', '메타', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_META', '페이스북', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_META', '인스타그램', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_AVGO', '브로드컴', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_AMD', '에이엠디', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_JPM', '제이피모건', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_JPM', 'JP모건', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('US_KO', '코카콜라', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('BOND_KR_GOV_3Y', '한국 국채', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('BOND_KR_GOV_10Y', '장기 국채', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('BOND_US_TREASURY_10Y', '미국 국채', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('BOND_US_TREASURY_20Y', '미국 장기채', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CASH_KRW', '현금', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CASH_USD', '달러', 'ko-KR', 'CURATED_SEED', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Figma 나만의 ETF/인기 ETF 화면용 개발 시드.
-- 실제 상품이 아니라 화면 연동과 API 개발 검증을 위한 curated discovery ETF 데이터다.
MERGE INTO managed_etfs (etf_code, owner_user_id, source_type, title, theme, benchmark, period, risk_level, return_rate, popularity_score, favorite_count, image_url, short_description, holdings_json, trend_points_json, analysis_summary_json, last_report_id, published_at, created_at, updated_at) KEY(etf_code) VALUES
('ETF_AI_TECH', NULL, 'DISCOVERY', 'AI 테크', '기술', 'SP500', '1Y', '매우 낮음', 24.8, 100, 9999, NULL,
'전 세계 AI 혁명을 주도하는 반도체 및 소프트웨어 핵심 기업에 집중 투자하는 포트폴리오입니다.',
'[{"stockId":"US_NVDA","weight":35,"changeRate":39.0},{"stockId":"US_MSFT","weight":25,"changeRate":18.4},{"stockId":"US_AAPL","weight":20,"changeRate":12.1},{"stockId":"US_GOOGL","weight":20,"changeRate":9.6}]',
'[{"date":"2025-05-10","value":100.0},{"date":"2025-08-10","value":108.0},{"date":"2025-11-10","value":116.0},{"date":"2026-02-10","value":119.5},{"date":"2026-05-10","value":124.8}]',
'[{"tag":"반도체"},{"tag":"빅테크"},{"tag":"LLM"},{"tag":"성장주"},{"badge":"인기"},{"subtitle":"성장 중심"},{"description":"전 세계 AI 혁명을 주도하는 반도체 및 소프트웨어 핵심 기업에 집중 투자하는 포트폴리오입니다."}]',
NULL, TIMESTAMP '2026-05-10 09:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ETF_DIVIDEND_ARISTOCRATS', NULL, 'DISCOVERY', '배당 귀족', '배당', 'SP500', '1Y', '낮음', 8.7, 92, 7420, NULL,
'현금 흐름이 탄탄한 배당주 중심 포트폴리오입니다.',
'[{"stockId":"US_KO","weight":45,"changeRate":4.2},{"stockId":"US_JPM","weight":30,"changeRate":7.6},{"stockId":"KRX_105560","weight":15,"changeRate":5.8},{"stockId":"KRX_055550","weight":10,"changeRate":3.4}]',
'[{"date":"2025-05-10","value":100.0},{"date":"2025-08-10","value":102.4},{"date":"2025-11-10","value":104.1},{"date":"2026-02-10","value":106.6},{"date":"2026-05-10","value":108.7}]',
'[{"tag":"배당"},{"tag":"현금흐름"},{"tag":"방어주"},{"badge":"안정"},{"subtitle":"현금 흐름"},{"description":"현금 흐름이 탄탄한 배당주 중심 포트폴리오입니다."}]',
NULL, TIMESTAMP '2026-05-10 08:50:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ETF_BIG_TECH_7', NULL, 'DISCOVERY', '빅테크 7', '기술', 'NASDAQ', '1Y', '보통', 18.3, 88, 6810, NULL,
'미국 대형 기술주 7개를 중심으로 시장 주도 기업에 투자하는 포트폴리오입니다.',
'[{"stockId":"US_AAPL","weight":18,"changeRate":12.1},{"stockId":"US_MSFT","weight":18,"changeRate":18.4},{"stockId":"US_NVDA","weight":18,"changeRate":39.0},{"stockId":"US_AMZN","weight":14,"changeRate":16.2},{"stockId":"US_GOOGL","weight":12,"changeRate":9.6},{"stockId":"US_META","weight":12,"changeRate":21.3},{"stockId":"US_TSLA","weight":8,"changeRate":-6.4}]',
'[{"date":"2025-05-10","value":100.0},{"date":"2025-08-10","value":106.0},{"date":"2025-11-10","value":111.2},{"date":"2026-02-10","value":114.0},{"date":"2026-05-10","value":118.3}]',
'[{"tag":"빅테크"},{"tag":"나스닥"},{"tag":"성장주"},{"badge":"인기"},{"subtitle":"시장 주도"},{"description":"미국 대형 기술주 7개를 중심으로 시장 주도 기업에 투자하는 포트폴리오입니다."}]',
NULL, TIMESTAMP '2026-05-10 08:40:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ETF_SEMICONDUCTOR_CHAIN', NULL, 'DISCOVERY', '반도체 밸류체인', '반도체', 'NASDAQ', '1Y', '보통', 12.5, 84, 5600, NULL,
'반도체 설계, 장비, 메모리 기업을 함께 담은 밸류체인 포트폴리오입니다.',
'[{"stockId":"US_NVDA","weight":28,"changeRate":39.0},{"stockId":"US_AVGO","weight":22,"changeRate":14.7},{"stockId":"US_AMD","weight":18,"changeRate":11.2},{"stockId":"KRX_005930","weight":17,"changeRate":6.4},{"stockId":"KRX_000660","weight":15,"changeRate":8.9}]',
'[{"date":"2025-05-10","value":100.0},{"date":"2025-08-10","value":103.0},{"date":"2025-11-10","value":108.4},{"date":"2026-02-10","value":110.1},{"date":"2026-05-10","value":112.5}]',
'[{"tag":"반도체"},{"tag":"기술"},{"tag":"밸류체인"},{"badge":"인기"},{"subtitle":"글로벌 유행"},{"description":"반도체 설계, 장비, 메모리 기업을 함께 담은 밸류체인 포트폴리오입니다."}]',
NULL, TIMESTAMP '2026-05-10 08:30:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ETF_GLOBAL_FINANCE', NULL, 'DISCOVERY', '글로벌 금융', '금융', 'SP500', '1Y', '낮음', 6.9, 77, 4200, NULL,
'미국과 한국의 대표 금융주를 섞은 안정형 포트폴리오입니다.',
'[{"stockId":"US_JPM","weight":45,"changeRate":7.6},{"stockId":"KRX_105560","weight":30,"changeRate":5.8},{"stockId":"KRX_055550","weight":25,"changeRate":3.4}]',
'[{"date":"2025-05-10","value":100.0},{"date":"2025-08-10","value":101.5},{"date":"2025-11-10","value":103.8},{"date":"2026-02-10","value":105.2},{"date":"2026-05-10","value":106.9}]',
'[{"tag":"금융"},{"tag":"은행"},{"tag":"안정"},{"badge":"안정"},{"subtitle":"금리 민감"},{"description":"미국과 한국의 대표 금융주를 섞은 안정형 포트폴리오입니다."}]',
NULL, TIMESTAMP '2026-05-10 08:20:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ETF_KOREA_BATTERY', NULL, 'DISCOVERY', '2차전지 성장', '2차전지', 'KOSPI', '1Y', '높음', -4.3, 70, 3900, NULL,
'국내 2차전지 소재와 완성차 관련 종목에 투자하는 변동성 높은 포트폴리오입니다.',
'[{"stockId":"KRX_051910","weight":30,"changeRate":-3.8},{"stockId":"KRX_006400","weight":25,"changeRate":-5.1},{"stockId":"KRX_086520","weight":25,"changeRate":-8.4},{"stockId":"KRX_005380","weight":20,"changeRate":4.6}]',
'[{"date":"2025-05-10","value":100.0},{"date":"2025-08-10","value":96.0},{"date":"2025-11-10","value":98.1},{"date":"2026-02-10","value":93.8},{"date":"2026-05-10","value":95.7}]',
'[{"tag":"2차전지"},{"tag":"전기차"},{"tag":"성장주"},{"badge":"변동성"},{"subtitle":"고성장"},{"description":"국내 2차전지 소재와 완성차 관련 종목에 투자하는 변동성 높은 포트폴리오입니다."}]',
NULL, TIMESTAMP '2026-05-10 08:10:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ETF_HEALTHCARE_DEFENSE', NULL, 'DISCOVERY', '헬스케어 방어', '헬스케어', 'KOSPI', '1Y', '낮음', 5.2, 64, 2500, NULL,
'시장 변동성이 커질 때 방어 성격을 기대할 수 있는 헬스케어 포트폴리오입니다.',
'[{"stockId":"KRX_068270","weight":45,"changeRate":5.7},{"stockId":"KRX_207940","weight":40,"changeRate":4.9},{"stockId":"US_KO","weight":15,"changeRate":4.2}]',
'[{"date":"2025-05-10","value":100.0},{"date":"2025-08-10","value":101.3},{"date":"2025-11-10","value":102.5},{"date":"2026-02-10","value":103.4},{"date":"2026-05-10","value":105.2}]',
'[{"tag":"헬스케어"},{"tag":"방어주"},{"tag":"안정"},{"badge":"방어"},{"subtitle":"방어 중심"},{"description":"시장 변동성이 커질 때 방어 성격을 기대할 수 있는 헬스케어 포트폴리오입니다."}]',
NULL, TIMESTAMP '2026-05-10 08:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ETF_GREEN_TRANSITION', NULL, 'DISCOVERY', '친환경 전환', '친환경', 'SP500', '1Y', '보통', 9.4, 58, 1900, NULL,
'전기차와 배터리 중심의 친환경 전환 테마 포트폴리오입니다.',
'[{"stockId":"US_TSLA","weight":35,"changeRate":-6.4},{"stockId":"KRX_006400","weight":25,"changeRate":-5.1},{"stockId":"KRX_051910","weight":20,"changeRate":-3.8},{"stockId":"KRX_005380","weight":20,"changeRate":4.6}]',
'[{"date":"2025-05-10","value":100.0},{"date":"2025-08-10","value":103.2},{"date":"2025-11-10","value":105.0},{"date":"2026-02-10","value":107.6},{"date":"2026-05-10","value":109.4}]',
'[{"tag":"친환경"},{"tag":"전기차"},{"tag":"배터리"},{"badge":"테마"},{"subtitle":"전환 성장"},{"description":"전기차와 배터리 중심의 친환경 전환 테마 포트폴리오입니다."}]',
NULL, TIMESTAMP '2026-05-10 07:50:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
