package com.uniport.service.backtest;

import java.math.BigDecimal;
import java.util.List;

public record BacktestResult(
        BigDecimal initialNavKrw,
        BigDecimal finalNavKrw,
        BigDecimal profitAmountKrw,
        BigDecimal totalReturnPercent,
        BigDecimal annualizedReturnPercent,
        BigDecimal volatilityPercent,
        BigDecimal maxDrawdownPercent,
        BigDecimal benchmarkReturnPercent,
        BigDecimal excessReturnPercent,
        BigDecimal sharpeRatio,
        BigDecimal hhi,
        String topHoldingName,
        BigDecimal topHoldingWeightPercent,
        BigDecimal top3WeightPercent,
        BigDecimal top5WeightPercent,
        String dominantSector,
        BigDecimal dominantSectorWeightPercent,
        BigDecimal effectiveHoldings,
        BigDecimal cashWeightPercent,
        BigDecimal benchmarkAnnualizedReturnPercent,
        BigDecimal benchmarkVolatilityPercent,
        BigDecimal benchmarkMaxDrawdownPercent,
        BigDecimal sortinoRatio,
        BigDecimal beta,
        BigDecimal trackingErrorPercent,
        BigDecimal informationRatio,
        BigDecimal winRatePercent,
        Integer riskScore,
        String riskGrade,
        String riskGradeLabel,
        Integer tradingDays,
        List<BacktestNavPoint> navSeries
) {
    public BacktestResult(BigDecimal initialNavKrw,
                          BigDecimal finalNavKrw,
                          BigDecimal profitAmountKrw,
                          BigDecimal totalReturnPercent,
                          BigDecimal annualizedReturnPercent,
                          BigDecimal volatilityPercent,
                          BigDecimal maxDrawdownPercent,
                          BigDecimal benchmarkReturnPercent,
                          BigDecimal excessReturnPercent,
                          BigDecimal sharpeRatio,
                          BigDecimal hhi,
                          String topHoldingName,
                          BigDecimal topHoldingWeightPercent,
                          BigDecimal top3WeightPercent,
                          String dominantSector,
                          BigDecimal dominantSectorWeightPercent,
                          Integer riskScore,
                          String riskGrade,
                          String riskGradeLabel,
                          Integer tradingDays,
                          List<BacktestNavPoint> navSeries) {
        this(
                initialNavKrw,
                finalNavKrw,
                profitAmountKrw,
                totalReturnPercent,
                annualizedReturnPercent,
                volatilityPercent,
                maxDrawdownPercent,
                benchmarkReturnPercent,
                excessReturnPercent,
                sharpeRatio,
                hhi,
                topHoldingName,
                topHoldingWeightPercent,
                top3WeightPercent,
                top3WeightPercent,
                dominantSector,
                dominantSectorWeightPercent,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                riskScore,
                riskGrade,
                riskGradeLabel,
                tradingDays,
                navSeries
        );
    }
}
